### ISSUE TITLE
Attributes Should Be Order-Preserving

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#19]
Even though XML itself doesn't guarantee order preservation during attribute parsing, we should probably still try to achieve it ourselves within the `Attributes` data structure.  Harry H makes a pretty compelling argument here w.r.t. string comparison (in testing) as well as just the principle of least surprise.  Fundamentally, there's no way we can correct the issue if an underlying parser implementation decides to reorder attributes, but we can at least preserve order through our _own_ code.

Spec:

``` scala
forAll { pairs: List[(QName, String)] =>
  Attributes(pairs: _*).toList mustEqual pairs
}
```

**Comment by ebruchez** [comment]
Excellent, that's the right decision :)

**Comment by josharnold52** [comment]
I'm not sure if this is what you had in mind, but I took a stab at resolving this by creating a persistent analog of LinkedHashMap.   The code is in my [order-attr](https://github.com/josharnold52/anti-xml/tree/order-attr) branch;  the meat of it is in [OrderPreservingMap](https://github.com/josharnold52/anti-xml/blob/order-attr/src/main/scala/com/codecommit/antixml/util/OrderPreservingMap.scala) and [LinkedOrderPreservingMap](https://github.com/josharnold52/anti-xml/blob/order-attr/src/main/scala/com/codecommit/antixml/util/LinkedOrderPreservingMap.scala).

The map uses Scala's default immutable Map internally and offers the same asymptotic characteristics, albeit with a larger constant factor (particularly for structural update operations).  

I haven't run any extensive performance tests, but I did try using Anti-XML's "load" performance trials to get a measure of memory footprint and creation time.  The 7MB file doesn't contain attributes and wasn't very interesting. ;)  However, the 30MB file made for a pretty good test.  Many of its elements have attributes, and many of those attribute maps exceed the size of my small-map optimizations:

```
Test                     master   order-attr     Increase

loadLarge-size (MB)         174         194       11.5 %
loadLarge-time (ms)        2405        2795       16.2 %
loadLarge-StAX-time (ms)   2308        2627       13.8 %
```

The first column contains the results for the baseline code, and the second column contains the results using the new map.  Both branches included the #32 change.  As can be seen, the new map results in a 11.5% increase in memory and about a 15% increase in load time.   

If you think this approach is in the ballpark, I have some ideas for how to reduce those numbers, but I thought I'd look for some feedback before going further :)

**Comment by djspiewak** [comment]
Very nice!  Sorry for the delay; it took me a little while to find the time to dig into this, but it looks really good!  It would be nice if we could improve those performance numbers, but I think this is definitely an awesome starting point.

Do we want to merge this in soon and continue to improve, or should we wait?  It's up to you.

**Comment by josharnold52** [comment]
I went ahead with a few performance improvements:
1.  The next and previous links are now stored as type `Key` rather than `Option[Key]`, which cuts the additional memory footprint in half on hotspot.
2.  The boundary nodes are no longer kept in the underlying map, which allows me to add a new entry with only one update of the underlying map.  This makes the build time very close to what it was.

By pure coincidence, the 'loadLarge'  trial now shows a _decrease_ in memory usage compared to when it used a standard scala Map.   It turns out all of the elements in that file have either 0 or 5 attributes.    In the 5-entry case, the underlying map is of size 3, which is small enough for scala to use a special implementation, resulting in a net decrease.  I spent a long time thinking I had broke something before figuring that one out :)
