### ISSUE TITLE
Add Single-Level Select Operation on Selectable

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/anti-xml#47]
We need a single-level select operation on `Selectable` that functions exactly like `collect` except that it returns a `DeepZipper` rather than merely a `Group`.  The method for this operation should be named `select`.

**Comment by josharnold52** [comment]
Note that `\` has higher precedence than letters so `select` won't always compose syntactically with the other operations;  I believe we thought otherwise when we discussed the name in #38.

That said, I'm still in favor of keeping `select` for the time being.   An operator synonym can always be added later if it becomes annoying.

**Comment by djspiewak** [comment]
Actually, I was thinking about the precedence issue too.  The `select` name dates back several months; I think Jorge Ortiz actually devised it.  It's true that it doesn't compose well with the other operators, but I think that's a fairly rare case due to the non-descending nature of the operation.  We can reassess if we find this not to be the case.

**Comment by josharnold52** [comment]
Pull request #65 adds this operator.
